spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: info

cleaner:
  cron: 0 0 2 * * ?

hash:
  batch:
    size: 100
  cache:
    size: 100
    refill-threshold: 0.2

redis:
  repository:
    key-prefix: "url:"
    ttl: 72

base62:
  encoder:
    charset: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

async:
  executor:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    thread-name-prefix: url-shortener-async-
    keep-alive-seconds: 60

short:
  url:
     prefix: "http://short.com/"
     lifetime: 90
